import { DefaultTheme } from 'styled-components'

export const lightTheme: DefaultTheme = {
  background: '#FFFFFF',
  textColor: '#333333',
  input: '#E8EAEF',
  placeholder: '#7E8496',
  card: '#E8EAEF',
  border: '#9BA5B4',
  palette01: '#FF6663',
  palette02: '#FEB144',
  palette03: '#FEF44E',
  palette04: '#9EE09E',
  palette05: '#9EC1CF',
  palette06: '#CC99C9',
  palette07: '#FFFFFF',
  palette08: '#333333',
  modalBackground: '#ffffff',
  modalOverlay: 'rgba(0,0,0,0.6)',
  modalText: '#333333',
  main01: '#FA5E54',
  main02: '#FFCE50',
  buttonText: '#FFFFFF',
  arrow: '/assets/icons/light-arrow.png',
  back: '/assets/icons/light-back.png',
  close: '/assets/icons/light-close.png',
  dots: '/assets/icons/light-dots.png',
  downArrow: '/assets/icons/light-down-arrow.png',
  followers: '/assets/icons/light-followers.png',
  hidePw: '/assets/icons/light-hide-password.png',
  showPw: '/assets/icons/light-show-password.png',
  home: '/assets/icons/light-home-nav.png',
  like: '/assets/icons/light-like.png',
  logo: '/assets/icons/light-logo.png',
  showDiary: '/assets/icons/light-show-diary.png',
  bubble: '/assets/icons/light-speech-bubble.png',
  user: '/assets/icons/light-user.png',
  write: '/assets/icons/light-write-nav.png',
}

export const darkTheme: DefaultTheme = {
  background: '#252A38',
  textColor: '#FFFFFF',
  input: '#3F4D62',
  placeholder: '#9BA5B4',
  card: '#3F4D62',
  border: '#9BA5B4',
  palette01: '#FF6663',
  palette02: '#FEB144',
  palette03: '#FEF44E',
  palette04: '#9EE09E',
  palette05: '#9EC1CF',
  palette06: '#CC99C9',
  palette07: '#FFFFFF',
  palette08: '#333333',
  modalBackground: '#ffffff',
  modalOverlay: 'rgba(0,0,0,0.6)',
  modalText: '#333333',
  main01: '#FA5E54',
  main02: '#FFCE50',
  buttonText: '#FFFFFF',
  arrow: '/assets/icons/dark-arrow.png',
  back: '/assets/icons/dark-back.png',
  close: '/assets/icons/dark-close.png',
  dots: '/assets/icons/dark-dots.png',
  downArrow: '/assets/icons/dark-down-arrow.png',
  followers: '/assets/icons/dark-followers.png',
  hidePw: '/assets/icons/dark-hide-password.png',
  showPw: '/assets/icons/dark-show-password.png',
  home: '/assets/icons/dark-home-nav.png',
  like: '/assets/icons/dark-like.png',
  logo: '/assets/icons/dark-logo.png',
  showDiary: '/assets/icons/dark-show-diary.png',
  bubble: '/assets/icons/dark-speech-bubble.png',
  user: '/assets/icons/dark-user.png',
  write: '/assets/icons/dark-write-nav.png',
}
